// Curated lowercase wordlist used for passphrase generation.
// Keep ASCII-only, safe for terminals. This is a medium-sized sample list.
// For production, consider expanding further.

pub static WORDS: &[&str] = &[
    "able", "about", "above", "absent", "accent", "accept", "access", "accord", "account",
    "achieve", "acorn", "across", "act", "action", "active", "actor", "adapt", "add", "adder",
    "addition", "adjust", "admire", "admit", "adore", "adult", "advance", "advice", "aerial",
    "affair", "afford", "afraid", "after", "again", "agent", "agree", "ahead", "aim", "air",
    "aisle", "alarm", "album", "alert", "alien", "align", "alley", "allow", "almond", "alpha",
    "altar", "alter", "amber", "amend", "amid", "amount", "amuse", "anchor", "ancient", "angel",
    "angle", "animal", "ankle", "answer", "ant", "any", "apart", "apex", "apple", "april",
    "arcade", "arch", "area", "arena", "argue", "arise", "armor", "around", "arrive", "arrow",
    "artist", "aspect", "asset", "assist", "assume", "aster", "atlas", "atom", "attach", "attack",
    "attempt", "attic", "audio", "august", "aunt", "author", "autumn", "avenue", "avoid", "awake",
    "award", "aware", "baby", "bacon", "badge", "bag", "baker", "balance", "balcony", "ball",
    "bamboo", "banana", "banner", "bar", "bare", "bargain", "barn", "barrel", "base", "basic",
    "basket", "bath", "battle", "beach", "beacon", "bead", "beam", "bean", "bear", "beard",
    "beast", "beat", "beauty", "become", "bed", "beef", "before", "begin", "behave", "being",
    "believe", "bell", "belong", "below", "belt", "bench", "benefit", "berry", "beside", "best",
    "betray", "better", "between", "beyond", "bicycle", "bid", "big", "bike", "bill", "bind",
    "bird", "birth", "bison", "bit", "black", "blade", "blank", "blaze", "blend", "bless", "blind",
    "blink", "block", "blood", "bloom", "blossom", "blue", "board", "boat", "body", "boil", "bold",
    "bolt", "bomb", "bond", "bone", "bonus", "book", "boost", "border", "born", "borrow", "boss",
    "both", "bother", "bottle", "bottom", "bounce", "box", "boy", "brain", "branch", "brand",
    "brave", "bread", "break", "breathe", "breeze", "brick", "bridge", "brief", "bright", "bring",
    "brisk", "broad", "broken", "bronze", "broom", "brown", "brush", "bubble", "buddy", "budget",
    "buffalo", "build", "bulb", "bulk", "bullet", "bundle", "bunny", "burden", "burger", "burn",
    "burst", "bus", "bush", "business", "busy", "butter", "button", "buzz", "cable", "cactus",
    "cafe", "cage", "cake", "calm", "camera", "camp", "canal", "candle", "candy", "canvas",
    "canyon", "cap", "capable", "capital", "captain", "car", "carbon", "card", "care", "cargo",
    "carpet", "carry", "cart", "carve", "case", "cash", "castle", "casual", "cat", "catalog",
    "catch", "category", "cattle", "cause", "cave", "ceiling", "cell", "cement", "census",
    "center", "century", "ceramic", "chain", "chair", "chalk", "champion", "chance", "change",
    "chaos", "chapter", "charge", "charm", "chart", "chase", "chat", "cheap", "check", "cheer",
    "cheese", "chef", "cherry", "chest", "chicken", "chief", "child", "chimney", "choice",
    "choose", "chop", "chorus", "chosen", "chrome", "cigar", "cinema", "circle", "citizen", "city",
    "civil", "claim", "clap", "clarify", "clash", "claw", "clay", "clean", "clear", "clerk",
    "clever", "click", "client", "cliff", "climb", "clinic", "clock", "clone", "close", "cloth",
    "cloud", "clown", "club", "clue", "cluster", "coach", "coal", "coast", "coat", "coconut",
    "code", "coffee", "coil", "coin", "cold", "collar", "collect", "color", "column", "combine",
    "come", "comet", "comfort", "comic", "common", "compass", "copy", "coral", "core", "corner",
    "correct", "cotton", "couch", "cough", "count", "couple", "course", "cousin", "cover",
    "coyote", "crack", "cradle", "craft", "crane", "crash", "crate", "crave", "crawl", "crazy",
    "cream", "credit", "creek", "crew", "cricket", "crime", "crimson", "crisp", "critic", "crop",
    "cross", "crouch", "crow", "crown", "crucial", "cruise", "crumb", "crystal", "cube", "culture",
    "cup", "cupboard", "curious", "current", "curtain", "curve", "cushion", "custom", "cute",
    "cycle", "dad", "daily", "daisy", "dance", "danger", "dart", "dash", "data", "date",
    "daughter", "dawn", "day", "debit", "debris", "decade", "decide", "deck", "decorate", "deer",
    "defend", "define", "degree", "delay", "deliver", "delta", "demand", "denim", "dent", "deny",
    "depart", "depend", "deposit", "derive", "desk", "desert", "design", "desk", "detail",
    "detect", "develop", "device", "devote", "diagram", "dial", "diamond", "diary", "dice",
    "diesel", "diet", "differ", "digital", "dignity", "dilemma",
];
